# Generated by Django 2.2.7 on 2019-11-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvote',
            old_name='voter',
            new_name='voted_user',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='voter',
            new_name='voted_user',
        ),
    ]
